steps:
  - label: "Intel GPU Test"
    depends_on: []
    soft_fail: true
    agents:
     queue: "intel-xpu-kubevirt"
    commands: 
    - sh .buildkite/scripts/hardware_ci/run-xpu-test.sh
    env:
      DOCKER_HOST: tcp://localhost:2375
    image: docker:29.2-cli
    secrets:
      - REGISTRY
      - BUILDKITE_AGENT_TOKEN
    plugins:
      - kubernetes:
          podSpecPatch:
            containers:
            - name: container-0    # <-- Specify this exactly as `container-0`.
              resources:           #     Currently under experimentation to make this more ergonomic.
                requests:
                  "gpu.intel.com/i915": "2"
                limits:
                  "gpu.intel.com/i915": "2"
          sidecars:
          - image: docker:dind
            command:
            - sh
            - -c
            - |
              mkdir -p /etc/docker
              cat > /etc/docker/daemon.json <<EOF
              {
                "ipv6": false,
                "storage-driver": "overlay2"
              }
              EOF
              dockerd-entrypoint.sh
            securityContext:
              privileged: true
            env:
              - name: DOCKER_TLS_CERTDIR
                value: ""
            readinessProbe:
              exec:
                command:
                - docker
                - info
              initialDelaySeconds: 5
              periodSeconds: 5
              failureThreshold: 10