steps:
  - label: "Intel GPU Test"
    depends_on: []
    soft_fail: true
    agents:
     queue: "intel-xpu-kubevirt"
    commands: 
    - echo "Running Intel GPU tests..."
    - docker images
    env:
      DOCKER_HOST: tcp://localhost:2375
    plugins:
      - kubernetes:
          sidecars:
          - image: docker:dind
            command: [dockerd-entrypoint.sh]
            securityContext:
              privileged: true
            env:
              - name: DOCKER_TLS_CERTDIR
                value: ""
