steps:
  - label: "Build Container"
    key: "build-container"
    agents:
      queue: "docker-build"
    commands:
      - sh .buildkite/scripts/hardware_ci/build-container.sh
    secrets:
      - REGISTRY_TOKEN
      - REGISTRY_USER
      - REGISTRY
    plugins:
      - kubernetes:
          podSpecPatch:
            containers:
            - name: container-0
              image: moby/buildkit:latest   # buildctl is the only tool needed here
              resources:
                requests:
                  cpu: "8"
                  memory: "16Gi"

  - label: "Offline Inference - Basic"
    depends_on: "build-container"
    soft_fail: true
    agents:
      queue: "intel-xpu-kubevirt"
    commands:
      - sh .buildkite/scripts/hardware_ci/run-xpu-test.sh offline-basic
    secrets:
      - REGISTRY_TOKEN
      - HF_TOKEN
      - REGISTRY_USER
      - REGISTRY
    plugins:
      - kubernetes:
          podSpecPatch:
            imagePullSecrets:
              - name: sharvilshah-1-pull-secret
            containers:
            - name: container-0
              image: quay.io/sharvilshah-1/vllm-ci:${BUILDKITE_COMMIT}
              resources:
                requests:
                  "gpu.intel.com/i915": "2"
                  cpu: "32"
                  memory: "16Gi"
                limits:
                  "gpu.intel.com/i915": "2"
              hostIPC: true
              volumeMounts:
              - mountPath: /buildkite/workspace
                name: workspace

  - label: "Offline Inference - Distributed"
    depends_on: "build-container"
    soft_fail: true
    agents:
      queue: "intel-xpu-kubevirt"
    commands:
      - sh .buildkite/scripts/hardware_ci/run-xpu-test.sh offline-distributed
    secrets:
      - REGISTRY_TOKEN
      - HF_TOKEN
      - REGISTRY_USER
      - REGISTRY
    plugins:
      - kubernetes:
          podSpecPatch:
            imagePullSecrets:
              - name: sharvilshah-1-pull-secret
            containers:
            - name: container-0
              image: quay.io/sharvilshah-1/vllm-ci:${BUILDKITE_COMMIT}
              resources:
                requests:
                  "gpu.intel.com/i915": "2"
                  cpu: "32"
                  memory: "16Gi"
                limits:
                  "gpu.intel.com/i915": "2"
              hostIPC: true
              volumeMounts:
              - mountPath: /buildkite/workspace
                name: workspace

  - label: "Pytest - Core & Engine"
    depends_on: "build-container"
    soft_fail: true
    agents:
      queue: "intel-xpu-kubevirt"
    commands:
      - sh .buildkite/scripts/hardware_ci/run-xpu-test.sh pytest-core-engine
    secrets:
      - REGISTRY_TOKEN
      - HF_TOKEN
      - REGISTRY_USER
      - REGISTRY
    plugins:
      - kubernetes:
          podSpecPatch:
            imagePullSecrets:
              - name: sharvilshah-1-pull-secret
            containers:
            - name: container-0
              image: quay.io/sharvilshah-1/vllm-ci:${BUILDKITE_COMMIT}
              resources:
                requests:
                  "gpu.intel.com/i915": "2"
                  cpu: "32"
                  memory: "16Gi"
                limits:
                  "gpu.intel.com/i915": "2"
              hostIPC: true
              volumeMounts:
              - mountPath: /buildkite/workspace
                name: workspace

  - label: "Pytest - Sample & Worker"
    depends_on: "build-container"
    soft_fail: true
    agents:
      queue: "intel-xpu-kubevirt"
    commands:
      - sh .buildkite/scripts/hardware_ci/run-xpu-test.sh pytest-sample-worker
    secrets:
      - REGISTRY_TOKEN
      - HF_TOKEN
      - REGISTRY_USER
      - REGISTRY
    plugins:
      - kubernetes:
          podSpecPatch:
            imagePullSecrets:
              - name: sharvilshah-1-pull-secret
            containers:
            - name: container-0
              image: quay.io/sharvilshah-1/vllm-ci:${BUILDKITE_COMMIT}
              resources:
                requests:
                  "gpu.intel.com/i915": "2"
                  cpu: "32"
                  memory: "16Gi"
                limits:
                  "gpu.intel.com/i915": "2"
              hostIPC: true
              volumeMounts:
              - mountPath: /buildkite/workspace
                name: workspace

  - label: "Pytest - Structured Output & Spec Decode"
    depends_on: "build-container"
    soft_fail: true
    agents:
      queue: "intel-xpu-kubevirt"
    commands:
      - sh .buildkite/scripts/hardware_ci/run-xpu-test.sh pytest-spec-structured
    secrets:
      - REGISTRY_TOKEN
      - HF_TOKEN
      - REGISTRY_USER
      - REGISTRY
    plugins:
      - kubernetes:
          podSpecPatch:
            imagePullSecrets:
              - name: sharvilshah-1-pull-secret
            containers:
            - name: container-0
              image: quay.io/sharvilshah-1/vllm-ci:${BUILDKITE_COMMIT}
              resources:
                requests:
                  "gpu.intel.com/i915": "2"
                  cpu: "32"
                  memory: "16Gi"
                limits:
                  "gpu.intel.com/i915": "2"
              hostIPC: true
              volumeMounts:
              - mountPath: /buildkite/workspace
                name: workspace

  - label: "Pytest - KV Connector & Serial Utils"
    depends_on: "build-container"
    soft_fail: true
    agents:
      queue: "intel-xpu-kubevirt"
    commands:
      - sh .buildkite/scripts/hardware_ci/run-xpu-test.sh pytest-kv-serial
    secrets:
      - REGISTRY_TOKEN
      - HF_TOKEN
      - REGISTRY_USER
      - REGISTRY
    plugins:
      - kubernetes:
          podSpecPatch:
            imagePullSecrets:
              - name: sharvilshah-1-pull-secret
            containers:
            - name: container-0
              image: quay.io/sharvilshah-1/vllm-ci:${BUILDKITE_COMMIT}
              resources:
                requests:
                  "gpu.intel.com/i915": "2"
                  cpu: "32"
                  memory: "16Gi"
                limits:
                  "gpu.intel.com/i915": "2"
              hostIPC: true
              volumeMounts:
              - mountPath: /buildkite/workspace
                name: workspace

