steps:
  - label: "Intel GPU Test"
    depends_on: []
    soft_fail: true
    agents:
     queue: "intel-xpu-kubevirt"
    commands: 
    - sh .buildkite/scripts/hardware_ci/run-xpu-test.sh
    env:
      DOCKER_HOST: tcp://localhost:2375
    image: docker:29.2-cli
    plugins:
      - kubernetes:
          sidecars:
          - image: docker:dind
            command: [dockerd-entrypoint.sh]
            securityContext:
              privileged: true
            env:
              - name: DOCKER_TLS_CERTDIR
                value: ""
